source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'

target 'QTPaySDKDemo' do
  pod "QTPaySDK_UI_All", :path => "../"
  pod 'UIAlertView+Blocks'
  pod 'AFNetworking'
  pod 'MBProgressHUD'
end

target 'QTPaySDKDemoTests' do
  pod "QTPaySDK_UI_All", :path => "../"
end